name: roboshop
services:
  mongodb:
    build: ./mongodb
    image: mrmotam/mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb
  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis
  mysql:
    build: ./mysql
    image: mrmotam/mysql:v1
    container_name: mysql
    command: --mysql-native-password=ON --innodb-lock_wait_timeout=120  
    environment:
      MYSQL_ROOT_PASSWORD: 'RoboShop@1'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s
    volumes:
      - mysql
  rabbitmq:
    image: rabbitmq:4.3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "roboshop"
      RABBITMQ_DEFAULT_PASS: "roboshop123"
    volumes:
      - rabbitmq
  catalogue:
    build: ./catalogue
    image: mrmotam/catalogue:v1
    container_name: catalogue
    environment:
      MONGO: true
      MONGO_URL: "mongodb://mongodb:27017/catalogue"
    depends_on:
      - mongodb
  user:
    build: ./user
    image: mrmotam/user:v1
    container_name: user
    environment:
      MONGO: "true"
      MONGO_URL: "mongodb://mongodb:27017/users"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - mongodb
      - redis
  cart:
    build: ./cart
    image: mrmotam/cart:v1
    container_name: cart
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
      CATALOGUE_PORT: 8080
    depends_on:
      - redis
      - catalogue
  shipping:
    build: ./shipping
    image: mrmotam/shipping:v1
    container_name: shipping
    environment:
      CART_ENDPOINT: "cart:8080"
      DB_HOST: mysql
    depends_on:
    - cart
    - mysql      
  payment:
    build: ./payment
    image: mrmotam/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
      - rabbitmq
      - cart
      - user
  frontend:
    build: ./frontend
    image: mrmotam/frontend:v2
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
networks:
  default:
    name: robostore
    driver: bridge
    external: false
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:
